name: Full Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Use Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - run: npm ci
    - run: npm run build-webview
    - run: npm run build-cli
    - run: npm run lint
    - run: npm run package
    - run: python -m pip install -e .[dev]
    - run: xvfb-run -a npm run test -- packages/poml/tests
      if: runner.os == 'Linux'
    - run: npm run test -- packages/poml/tests
      if: runner.os != 'Linux'
    - run: python -m pytest python/tests
    - run: xvfb-run -a npm run compile && xvfb-run -a npm run test-vscode
      if: runner.os == 'Linux'
    - run: npm run compile && npm run test-vscode
      if: runner.os != 'Linux'
